/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rafaeljpc.traffic.controller

import java.time.Duration

fun main() {
    TrafficControl(
        Duration.ofSeconds(2),
        Duration.ofSeconds(1),
    ).start()
}
